AWSTemplateFormatVersion: "2010-09-09"
Description: "Create secret to be used by the Lambda. - (v1.0.0)"
Parameters:
  # General Configuration
  InfrastructureName:
    Type: "String"
    Description: "A name used to differentiate this infrastructure from other existing infrastructure."
    Default: "main"
  FunctionName:
    Type: "String"
    Description: "The name of the function."
  UserName:
    Type: "String"
    Description: "The Basic Auth. username."
  # Tag Configuration
  TagEnvironment:
    Type: "String"
    Description: "Which environment are we deploying to?"
Resources:
  Secret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: !Sub "lambda/${InfrastructureName}/basic-auth/${FunctionName}-${TagEnvironment}/credentials"
      KmsKeyId: !Sub "{{resolve:ssm:/kms/${InfrastructureName}/key/lambda/arn}}"
      Description: "The basic auth credentials for this function."
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"name": "${UserName}"}'
        GenerateStringKey: "pass"
        PasswordLength: 16
        ExcludeCharacters: '"@/\'
      Tags:
      - Key: "Name"
        Value: !Ref "AWS::StackName"
      - Key: "application"
        Value: !Ref "AWS::StackName"
      - Key: "contact-email"
        Value: !Sub "{{resolve:ssm:/account/${InfrastructureName}/tag/contact-email}}"
      - Key: "customer"
        Value: !Sub "{{resolve:ssm:/account/${InfrastructureName}/tag/customer}}"
      - Key: "environment"
        Value: !Ref TagEnvironment
      - Key: "team"
        Value: !Sub "{{resolve:ssm:/account/${InfrastructureName}/tag/team}}"
Outputs:
  SecretArn:
    Description: "The ARN for this secret."
    Value: !Ref Secret
    Export:
      Name: !Sub "${AWS::StackName}-SecretArn"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: "General Configuration"
      Parameters:
      - InfrastructureName
      - FunctionName
      - UserName 
    - Label:
        default: "Tag Configuration"
      Parameters:
      - TagEnvironment
    ParameterLabels:
      InfrastructureName:
        default: "Infrastructure Name:"
      FunctionName:
        default: "Function Name:"
      UserName:
        default: "User Name:"
      TagEnvironment:
        default: "Environment:"